apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server-app
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
        - name: server-app
          image: gcr.io/cobalt-bond-306109/server-app@sha256:33f50b61be1e8d50600f5bfcfb532209ebec22098811a2a252ccba1ef1200a9c
          ports:
            - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: server-app
spec:
  selector:
    app: server-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer #NodePort
