---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "server-app"
  namespace: "default"
  labels:
    app: "server-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "server-app"
  template:
    metadata:
      labels:
        app: "server-app"
    spec:
      containers:
      - name: "server-app-sha256-1"
        image: "gcr.io/cobalt-bond-306109/server-app@sha256:33f50b61be1e8d50600f5bfcfb532209ebec22098811a2a252ccba1ef1200a9c"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "server-app-hpa-ytpd"
  namespace: "default"
  labels:
    app: "server-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "server-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 3000
  type: LoadBalancer
